#if !defined(AFX_WAVEEDITOR_H__5065803B_FF5E_4AB1_B2C0_005BEAC30E8B__INCLUDED_)
#define AFX_WAVEEDITOR_H__5065803B_FF5E_4AB1_B2C0_005BEAC30E8B__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CWaveEditor wrapper class

class CWaveEditor : public CWnd
{
protected:
	DECLARE_DYNCREATE(CWaveEditor)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x9dff2541, 0x7756, 0x4f49, { 0xa9, 0x7f, 0xbb, 0xaf, 0x5f, 0x2c, 0x6d, 0xc4 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void AboutBox();
	long StartRecord();
	long StopRecord();
	long StartPlay();
	long StopPlay();
	long LoadWavFile(LPCTSTR filename);
	long SaveWavFile(LPCTSTR filename);
	long SelectWave(long startpoint, long endpoint);
	long LoadWavDlg();
	long SaveWavDlg();
	long LoadWithMask(LPCTSTR filename, LPCTSTR mask);
	long DelSelectWave();
	CString GetSelectedInfo();
	CString GetSelectedPath();
	long DrawPitch(LPCTSTR str);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_WAVEEDITOR_H__5065803B_FF5E_4AB1_B2C0_005BEAC30E8B__INCLUDED_)
